creation_rules:
  - gcp_kms: projects/braided-upgrade-435523-j8/locations/northamerica-northeast1/keyRings/ica2/cryptoKeys/ica2
    # Specify any file patterns you want to auto-encrypt
    path_regex: 'postgres-secrets'
    encrypted_regex: '^(data)$'     