apiVersion: v1
kind: Service
metadata:
  name: postgres-service # name of the service ( by using this name we can call it from different service )
  namespace: pg-ns # name of the namespace
spec:
  selector:
    app: postgres # name of the container (from the deployment)
  ports:
    - protocol: TCP
      port: 5432 # on this port our service will run 
      targetPort: 5432  # Container port
  type: ClusterIP # type of the service (1. Loadbalancer, 2. NodePort, 3. ClusterIP) 





  
# URL of service is in the below format:

# <service-name>.<namespace>.svc.cluster.local:<service-port>

# URL to a kubernetes service is service-name.namespace.svc.cluster.local:service-port where cluster.local is the kubernetes cluster name.