apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment ## name of the deployment.
  namespace: redis-ns ## name of the namespace
  labels:
    app: redis
spec:
  replicas: 1 # number of replicas
  selector:
    matchLabels:
      app: redis ## using this service will identify the pods related to this deployment 
  template: ## all pods will be created base on this template (means all pods will have same config)
    metadata:
      labels:
        app: redis
        env: dev # environment 
        version: "1.0.0"
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports: ## pods will be running on this port
        - containerPort: 6379 


---

apiVersion: v1
kind: Service
metadata:
  name: redis-service # name of the service ( by using this name we can call it from different service )
  namespace: redis-ns # name of the namespace
spec:
  selector:
    app: redis # name of the container (from the deployment)
  ports:
    - protocol: TCP
      port: 6379 # on this port our service will run 
      targetPort: 6379  # Container port
  type: ClusterIP # type of the service (1. Loadbalancer, 2. NodePort, 3. ClusterIP) 