apiVersion: v1
kind: Service
metadata:
  name: redis-service # name of the service ( by using this name we can call it from different service )
  namespace: redis-ns # name of the namespace
spec:
  selector:
    app: redis # name of the container (from the deployment)
  ports:
    - protocol: TCP
      port: 6379 # on this port our service will run 
      targetPort: 6379  # Container port
  type: ClusterIP # type of the service (1. Loadbalancer, 2. NodePort, 3. ClusterIP) 

